### ISSUE TITLE
VALID auto_pad value

### ISSUE THREAD

**Issue by igor-yusupov** [robertknight/rten#382]
I found an interesting [model](https://github.com/Picsart-AI-Research/MI-GAN/tree/main) for removing objects from image. I'm going to add it to comparisons-rten repo, I already prepared python code. But I got an error with converting:

```
Error converting "Constant" operator: Unsupported tensor data type uint8 for operator /Constant_8_output_0
```

[weights link](https://huggingface.co/andraniksargsyan/migan/resolve/main/migan_pipeline_v2.onnx)

**Comment by igor-yusupov** [comment]
Btw as I see this operator just returning constant value? https://github.com/onnx/onnx/blob/2b504f81f1cadb098e69b53b76e4e12b66a3bdbf/onnx/reference/ops/op_constant.py#L57

I can try to add it if you think that it's easy

**Comment by robertknight** [comment]
`Constant` operators in ONNX models are eliminated when converting to `.rten` and replaced with the value (weights, bias etc.) they emit. They end up as `ConstantNode` nodes in the converted graph. See the `constant_node_from_onnx_constant_op` function. In the `main` branch converting this uint8 `Constant` succeeds because int8 and uint8 tensors are now supported.

However there is a different error that gets reported after:

```
Error converting Conv operator /gaussian_blur/Conv: Unsupported auto_pad value VALID
Traceback (most recent call last):
  File "/Users/robert/.virtualenvs/wasnn/bin/rten-convert", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/robert/projects/rten/rten-convert/rten_convert/converter.py", line 1557, in main
    graph = graph_from_onnx_graph(model.graph)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/robert/projects/rten/rten-convert/rten_convert/converter.py", line 1148, in graph_from_onnx_graph
    raise ValueError(
ValueError: Errors occurred when converting 1 operators
```

From the list of values given [in the spec](https://onnx.ai/onnx/operators/onnx__Conv.html), only the "NOTSET" and "SAME_UPPER" values are currently supported.

The latest version of the [`Conv`](https://onnx.ai/onnx/operators/onnx__Conv.html) operator mentions "VALID" but doesn't say what it means. Older versions on the same page say VALID means no padding. Internally that could be handled similar to the way `Padding::Fixed` works when all the values are zero. The difference is that the number of padding sides isn't specified in the model (it adapts to the number of spatial dimensions in the input tensor). Feel free to have a go at implementing that.

**Comment by igor-yusupov** [comment]
Found an [illustration](https://stackoverflow.com/questions/37674306/what-is-the-difference-between-same-and-valid-padding-in-tf-nn-max-pool-of-t) of how VALID pading works. It seems that with stride=1 this mode is no different from just no padding. So I just removed that parameter and re-converted the onnx weights.

After that I ran into a bug during inference, some operators didn't handle int8, so I made a PR with fixes for that: https://github.com/robertknight/rten/pull/387

**Comment by robertknight** [comment]
> So I just removed that parameter and re-converted the onnx weights.

Do you have a link to the re-converted weights?

> After that I ran into a bug during inference, some operators didn't handle int8, so I made a PR with fixes for that: https://github.com/robertknight/rten/pull/387

Thanks. Does the model work as intended with those changes applied?

**Comment by igor-yusupov** [comment]
Yes, it works ok with the example images. I added [migan example](https://github.com/igor-yusupov/comparisons-rten/tree/migan/migan) in comparisons-rten. I have also provided links to images and weights

**Comment by igor-yusupov** [comment]
I looked at the weights with the netron app and saw that in this padding stride=1, so it seems it doesn't make sense to specify padding='valid'. So I removed the parameter in this [line of code](https://github.com/Picsart-AI-Research/MI-GAN/blob/main/scripts/create_onnx_pipeline.py#L115)

Moreover on my machine with this parameter I get an error when trying to convert weights. Maybe this parameter is for older versions of packages?

**Comment by igor-yusupov** [comment]
btw the author refers to this [code](https://github.com/yuval-alaluf/Attend-and-Excite/blob/main/utils/gaussian_smoothing.py#L71) and it doesn't have this parameter
